language: go
go: "-1.11.x"
before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
install:
- dep ensure
script:
- go build
deploy:
  provider: releases
  api_key: a847f97cf08033019ce4a904507c29496447a31f
  file: kubex
  on:
    repo: jawahars16/kubex
